In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
# to display the all entire tables :
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# or locally 
# with pd.option_context('display.max_rows', None, 'display.max_columns', None):  
#     display(df)

pd.options.display.float_format = '${:,.2f}'.format

## Charge BDD Danube

In [4]:
file_loc = r"C:\Users\ldecarva\Documents\Data\Danube\BDD\Ancienne version\Fichiers-BDD-architecturale-MApUCE-v1.15.2-archives\_240616_BddMAPUCE_MAP_V15.2-export.csv"

In [5]:
df = pd.read_csv(file_loc, sep=";", index_col="NUMERO_TYPOLOGIE")

## Study of roof pairs characteristics

In [6]:
# order by inputs in the first 4 columns and then the other variables in alphabetic order
col_ord = ['PERIODE','NOM_TYPOLOGIE','USAGE','TERRITOIRE','COMPACITE', 'COUVERTURE_ROUTE', 'DATES', 'DATE_DEBUT', 'DATE_FIN',
       'DISPOSITIF', 'DISPOSITIF1', 'DISPOSITIF2', 'DISPOSITIF3',
       'DISPOSITIF4', 'DISPOSITIF_MUR_OPTION1', 'DISPOSITIF_MUR_OPTION2',
       'DISPOSITIF_MUR_OPTION3', 'DISPOSITIF_TOIT_OPTION2',
       'DISPOSTIIF_TOIT_ OPTION1', 'EP_ISOLANT', 'EP_ISOLANT1', 'EP_ISOLANT2',
       'EP_ISOLANT3', 'EP_ISOLANT4', 'EP_PLANCHER_INTER', 'EP_PLANCHER_RDC',
       'EP_PORTEUR', 'EP_PORTEUR1', 'EP_PORTEUR2', 'EP_PORTEUR3',
       'EP_PORTEUR4', 'EP_RE', 'EP_RE1', 'EP_RE2', 'EP_RE3', 'EP_RE4', 'EP_RI',
       'EP_RI1', 'EP_RI2', 'EP_RI3', 'EP_RI4', 'ID_PLANCHER', 'ISOLANT',
       'ISOLANT1', 'ISOLANT2', 'ISOLANT3', 'ISOLANT4', 
       'NUMERO_PERIODE',   'PERMEABILITE',
       'PLANCHER', 'PLANCHER_INTERMEDIAIRE', 'PLANCHER_RDC', 'PORTEUR',
       'PORTEUR1', 'PORTEUR2', 'PORTEUR3', 'PORTEUR4', 'POURCENTAGE_VITRAGE',
       'PROTECTIONS_SOLAIRES', 'REVETEMENT_EXT', 'REVETEMENT_EXT1',
       'REVETEMENT_EXT2', 'REVETEMENT_EXT3', 'REVETEMENT_EXT4',
       'REVETEMENT_INT', 'REVETEMENT_INT1', 'REVETEMENT_INT2',
       'REVETEMENT_INT3', 'REVETEMENT_INT4',  'TERRITOIRE1',
       'TERRITOIRE_DESC', 'TERRITOIRE_SHORT_ID', 'TYPE_VITRAGE', 
       'VENTILATION']

df= df[col_ord].sort_values(['PERIODE', 'NOM_TYPOLOGIE',"USAGE","TERRITOIRE"])

In [7]:
len(df["DISPOSITIF3"].unique())

38

In [8]:
len(df["DISPOSTIIF_TOIT_ OPTION1"].unique())

38

In [9]:
len(df["DISPOSITIF_MUR_OPTION1"].unique())

63

In [10]:
len(df["PLANCHER"].unique())

11

In [11]:
df["arch"] = (df['PERIODE'] + "-" + 
              df['NOM_TYPOLOGIE'] + "-" +
              df['USAGE'] + "-" +
              df['TERRITOIRE'])
archs = df["arch"].unique()

In [12]:
# exclude cases with territoire France global
archs_nofr = [arch for arch in archs 
              if arch.split("-")[-1] != "FRANCE"]
len(archs_nofr)

123

In [13]:
# Take out the ceiling from the archetypes

start = ["-".join(arch.split("-")[:-1]) 
         for arch in archs_nofr
         ]
print(start[0])

ter_mur = ["_".join(arch.split("-")[-1].split("_")[:-1])
            for arch in archs_nofr 
          ]
print(ter_mur[0])

n = range(len(start))
arch_ter_murs = ['-'.join([start[i], ter_mur[i]]) for i in n]
arch_ter_murs[0]

P1-BA-BATIMENT AGRICOLE
FRANCE_BOIS

'P1-BA-BATIMENT AGRICOLE-FRANCE_BOIS'

In [14]:
# Take the set of the list

print(len(arch_ter_murs))
arch_ter_murs = set(arch_ter_murs)
print(len(arch_ter_murs))

123
84

In [15]:
# Group archetypes in pairs or group of three

two_ceilings = []
three_ceilings =[]
for arch_mur in arch_ter_murs:
    same_mur = []
    for arch in archs_nofr:
#         if arch.split("-")[-1] != "FRANCE":
        if arch_mur in arch:
            same_mur.append(arch)
    if len(same_mur) == 2:
        two_ceilings.append(same_mur)
    elif len(same_mur) > 2:
        three_ceilings.append(same_mur)
        
print("len two_ceilings is ", len(two_ceilings)) 
print("len three_ceilings is ", len(three_ceilings)) 

print("\nthree_ceilings:\n",three_ceilings)
print("\ntwo_ceilings\n",two_ceilings)

len two_ceilings is  40
len three_ceilings is  3

three_ceilings:
 [['P1-I-HABITAT-FRANCE_PIERRE_CALCAIRE_ARDOISE', 'P1-I-HABITAT-FRANCE_PIERRE_CALCAIRE_TUILE', 'P1-I-HABITAT-FRANCE_PIERRE_CALCAIRE_ZINC'], ['P1-I-CHATEAU-FRANCE_PIERRE_CALCAIRE_ARDOISE', 'P1-I-CHATEAU-FRANCE_PIERRE_CALCAIRE_TUILE', 'P1-I-CHATEAU-FRANCE_PIERRE_CALCAIRE_ZINC'], ['P1-I-TERTIAIRE-FRANCE_PIERRE_CALCAIRE_ARDOISE', 'P1-I-TERTIAIRE-FRANCE_PIERRE_CALCAIRE_TUILE', 'P1-I-TERTIAIRE-FRANCE_PIERRE_CALCAIRE_ZINC']]

two_ceilings
 [['P1-BA-BATIMENT AGRICOLE-FRANCE_PIERRE_CALCAIRE_ARDOISE', 'P1-BA-BATIMENT AGRICOLE-FRANCE_PIERRE_CALCAIRE_TUILE'], ['P7-I-HABITAT-FRANCE_ARDOISE', 'P7-I-HABITAT-FRANCE_TUILE'], ['P4-P-HABITAT-FRANCE_ARDOISE', 'P4-P-HABITAT-FRANCE_BRIQUE_TUILE'], ['P4-I-HABITAT-FRANCE_ARDOISE', 'P4-I-HABITAT-FRANCE_TUILE'], ['P6-I-HABITAT-FRANCE_ARDOISE', 'P6-I-HABITAT-FRANCE_TUILE'], ['P2-I-BATIMENT D ENSEIGNEMENT-FRANCE_ARDOISE', 'P2-I-BATIMENT D ENSEIGNEMENT-FRANCE_TUILE'], ['P3-I-HABITAT-FRANCE_ARDOISE', 'P3-I-HABITAT-FRANCE_TUILE'], ['P4-I-BATIMENT DE SANTE-FRANCE_ARDOISE', 'P4-I-BATIMENT DE SANTE-FRANCE_TUILE'], ['P6-I-BATIMENT DE SANTE-FRANCE_ARDOISE', 'P6-I-BATIMENT DE SANTE-FRANCE_TUILE'], ['P6-I-BATIMENT D ENSEIGNEMENT-FRANCE_ARDOISE', 'P6-I-BATIMENT D ENSEIGNEMENT-FRANCE_TUILE'], ['P1-BA-BATIMENT AGRICOLE-FRANCE_PIERRE_GRES_ARDOISE', 'P1-BA-BATIMENT AGRICOLE-FRANCE_PIERRE_GRES_TUILE'], ['P2-P-HABITAT-FRANCE_ARDOISE', 'P2-P-HABITAT-FRANCE_BRIQUE_TUILE'], ['P1-I-BATIMENT RELIGIEUX-FRANCE_PIERRE_ARDOISE', 'P1-I-BATIMENT RELIGIEUX-FRANCE_PIERRE_SCHISTE_TUILE'], ['P1-I-HABITAT-FRANCE_BOIS_ARDOISE', 'P1-I-HABITAT-FRANCE_BOIS_TUILE'], ['P1-BA-BATIMENT AGRICOLE-FRANCE_BOIS_ARDOISE', 'P1-BA-BATIMENT AGRICOLE-FRANCE_BOIS_TUILE'], ['P3-I-BATIMENT D ENSEIGNEMENT-FRANCE_ARDOISE', 'P3-I-BATIMENT D ENSEIGNEMENT-FRANCE_TUILE'], ['P5-I-BATIMENT DE SANTE-FRANCE_ARDOISE', 'P5-I-BATIMENT DE SANTE-FRANCE_TUILE'], ['P1-I-TERTIAIRE-FRANCE_BOIS_ARDOISE', 'P1-I-TERTIAIRE-FRANCE_BOIS_TUILE'], ['P7-P-HABITAT-FRANCE_ARDOISE', 'P7-P-HABITAT-FRANCE_BRIQUE_TUILE'], ['P6-P-HABITAT-FRANCE_ARDOISE', 'P6-P-HABITAT-FRANCE_BRIQUE_TUILE'], ['P1-I-HABITAT-FRANCE_PIERRE_GRANITE_ARDOISE', 'P1-I-HABITAT-FRANCE_PIERRE_GRANITE_TUILE'], ['P1-I-TERTIAIRE-FRANCE_PIERRE_GRANITE_ARDOISE', 'P1-I-TERTIAIRE-FRANCE_PIERRE_GRANITE_TUILE'], ['P1-P-HABITAT-FRANCE_PIERRE_GRANITE_ARDOISE', 'P1-P-HABITAT-FRANCE_PIERRE_GRANITE_TUILE'], ['P4-I-BATIMENT D ENSEIGNEMENT-FRANCE_ARDOISE', 'P4-I-BATIMENT D ENSEIGNEMENT-FRANCE_TUILE'], ['P2-I-HABITAT-FRANCE_ARDOISE', 'P2-I-HABITAT-FRANCE_TUILE'], ['P7-I-BATIMENT D ENSEIGNEMENT-FRANCE_ARDOISE', 'P7-I-BATIMENT D ENSEIGNEMENT-FRANCE_TUILE'], ['P3-P-HABITAT-FRANCE_ARDOISE', 'P3-P-HABITAT-FRANCE_BRIQUE_TUILE'], ['P5-P-HABITAT-FRANCE_ARDOISE', 'P5-P-HABITAT-FRANCE_BRIQUE_TUILE'], ['P7-I-BATIMENT DE SANTE-FRANCE_ARDOISE', 'P7-I-BATIMENT DE SANTE-FRANCE_TUILE'], ['P3-I-BATIMENT DE SANTE-FRANCE_ARDOISE', 'P3-I-BATIMENT DE SANTE-FRANCE_TUILE'], ['P1-P-HABITAT-FRANCE_PIERRE_GRES_ARDOISE', 'P1-P-HABITAT-FRANCE_PIERRE_GRES_TUILE'], ['P2-I-BATIMENT DE SANTE-FRANCE_ARDOISE', 'P2-I-BATIMENT DE SANTE-FRANCE_TUILE'], ['P1-I-CHATEAU-FRANCE_PIERRE_GRANITE_ARDOISE', 'P1-I-CHATEAU-FRANCE_PIERRE_GRANITE_TUILE'], ['P1-I-CHATEAU-FRANCE_PIERRE_GRES_ARDOISE', 'P1-I-CHATEAU-FRANCE_PIERRE_GRES_TUILE'], ['P1-I-HABITAT-FRANCE_PIERRE_GRES_ARDOISE', 'P1-I-HABITAT-FRANCE_PIERRE_GRES_TUILE'], ['P5-I-HABITAT-FRANCE_ARDOISE', 'P5-I-HABITAT-FRANCE_TUILE'], ['P1-BA-BATIMENT AGRICOLE-FRANCE_PIERRE_GRANITE_ARDOISE', 'P1-BA-BATIMENT AGRICOLE-FRANCE_PIERRE_GRANITE_TUILE'], ['P1-P-HABITAT-FRANCE_BOIS_ARDOISE', 'P1-P-HABITAT-FRANCE_BOIS_TUILE'], ['P5-I-BATIMENT D ENSEIGNEMENT-FRANCE_ARDOISE', 'P5-I-BATIMENT D ENSEIGNEMENT-FRANCE_TUILE'], ['P1-P-HABITAT-FRANCE_PIERRE_CALCAIRE_TUILE', 'P1-P-HABITAT-FRANCE_PIERRE_CALCAIRE_ZINC']]

In [16]:
# print cases in which the roofs have different properties (besides material)
for pair in two_ceilings:
    print('\n', "-"*100)
    for e in pair:
        print(e)
    
    df0 = df[df["arch"]==pair[0]]
    df1 = df[df["arch"]==pair[1]]
    pair_df = pd.concat([df0,df1])[["TERRITOIRE",
                                    "REVETEMENT_EXT3",
                                    "EP_RE3",
                                    "PORTEUR3",
                                    "EP_PORTEUR3",
                                    "ISOLANT3",
                                    "EP_ISOLANT3",
                                    "REVETEMENT_INT3",
                                    "EP_RI3",
                                    ]]
    if sum(pair_df.iloc[1][2:] != pair_df.iloc[0][2:]) != 0:
        display(pair_df)

 ----------------------------------------------------------------------------------------------------
P1-BA-BATIMENT AGRICOLE-FRANCE_PIERRE_CALCAIRE_ARDOISE
P1-BA-BATIMENT AGRICOLE-FRANCE_PIERRE_CALCAIRE_TUILE

 ----------------------------------------------------------------------------------------------------
P7-I-HABITAT-FRANCE_ARDOISE
P7-I-HABITAT-FRANCE_TUILE

 ----------------------------------------------------------------------------------------------------
P4-P-HABITAT-FRANCE_ARDOISE
P4-P-HABITAT-FRANCE_BRIQUE_TUILE

 ----------------------------------------------------------------------------------------------------
P4-I-HABITAT-FRANCE_ARDOISE
P4-I-HABITAT-FRANCE_TUILE

 ----------------------------------------------------------------------------------------------------
P6-I-HABITAT-FRANCE_ARDOISE
P6-I-HABITAT-FRANCE_TUILE

 ----------------------------------------------------------------------------------------------------
P2-I-BATIMENT D ENSEIGNEMENT-FRANCE_ARDOISE
P2-I-BATIMENT D ENSEIGNEMENT-FRANCE_TUILE

 ----------------------------------------------------------------------------------------------------
P3-I-HABITAT-FRANCE_ARDOISE
P3-I-HABITAT-FRANCE_TUILE

 ----------------------------------------------------------------------------------------------------
P4-I-BATIMENT DE SANTE-FRANCE_ARDOISE
P4-I-BATIMENT DE SANTE-FRANCE_TUILE

 ----------------------------------------------------------------------------------------------------
P6-I-BATIMENT DE SANTE-FRANCE_ARDOISE
P6-I-BATIMENT DE SANTE-FRANCE_TUILE

 ----------------------------------------------------------------------------------------------------
P6-I-BATIMENT D ENSEIGNEMENT-FRANCE_ARDOISE
P6-I-BATIMENT D ENSEIGNEMENT-FRANCE_TUILE

 ----------------------------------------------------------------------------------------------------
P1-BA-BATIMENT AGRICOLE-FRANCE_PIERRE_GRES_ARDOISE
P1-BA-BATIMENT AGRICOLE-FRANCE_PIERRE_GRES_TUILE

 ----------------------------------------------------------------------------------------------------
P2-P-HABITAT-FRANCE_ARDOISE
P2-P-HABITAT-FRANCE_BRIQUE_TUILE

 ----------------------------------------------------------------------------------------------------
P1-I-BATIMENT RELIGIEUX-FRANCE_PIERRE_ARDOISE
P1-I-BATIMENT RELIGIEUX-FRANCE_PIERRE_SCHISTE_TUILE

 ----------------------------------------------------------------------------------------------------
P1-I-HABITAT-FRANCE_BOIS_ARDOISE
P1-I-HABITAT-FRANCE_BOIS_TUILE

 ----------------------------------------------------------------------------------------------------
P1-BA-BATIMENT AGRICOLE-FRANCE_BOIS_ARDOISE
P1-BA-BATIMENT AGRICOLE-FRANCE_BOIS_TUILE

 ----------------------------------------------------------------------------------------------------
P3-I-BATIMENT D ENSEIGNEMENT-FRANCE_ARDOISE
P3-I-BATIMENT D ENSEIGNEMENT-FRANCE_TUILE

 ----------------------------------------------------------------------------------------------------
P5-I-BATIMENT DE SANTE-FRANCE_ARDOISE
P5-I-BATIMENT DE SANTE-FRANCE_TUILE

 ----------------------------------------------------------------------------------------------------
P1-I-TERTIAIRE-FRANCE_BOIS_ARDOISE
P1-I-TERTIAIRE-FRANCE_BOIS_TUILE

 ----------------------------------------------------------------------------------------------------
P7-P-HABITAT-FRANCE_ARDOISE
P7-P-HABITAT-FRANCE_BRIQUE_TUILE

 ----------------------------------------------------------------------------------------------------
P6-P-HABITAT-FRANCE_ARDOISE
P6-P-HABITAT-FRANCE_BRIQUE_TUILE

 ----------------------------------------------------------------------------------------------------
P1-I-HABITAT-FRANCE_PIERRE_GRANITE_ARDOISE
P1-I-HABITAT-FRANCE_PIERRE_GRANITE_TUILE

 ----------------------------------------------------------------------------------------------------
P1-I-TERTIAIRE-FRANCE_PIERRE_GRANITE_ARDOISE
P1-I-TERTIAIRE-FRANCE_PIERRE_GRANITE_TUILE

 ----------------------------------------------------------------------------------------------------
P1-P-HABITAT-FRANCE_PIERRE_GRANITE_ARDOISE
P1-P-HABITAT-FRANCE_PIERRE_GRANITE_TUILE

 ----------------------------------------------------------------------------------------------------
P4-I-BATIMENT D ENSEIGNEMENT-FRANCE_ARDOISE
P4-I-BATIMENT D ENSEIGNEMENT-FRANCE_TUILE

 ----------------------------------------------------------------------------------------------------
P2-I-HABITAT-FRANCE_ARDOISE
P2-I-HABITAT-FRANCE_TUILE

 ----------------------------------------------------------------------------------------------------
P7-I-BATIMENT D ENSEIGNEMENT-FRANCE_ARDOISE
P7-I-BATIMENT D ENSEIGNEMENT-FRANCE_TUILE

 ----------------------------------------------------------------------------------------------------
P3-P-HABITAT-FRANCE_ARDOISE
P3-P-HABITAT-FRANCE_BRIQUE_TUILE

 ----------------------------------------------------------------------------------------------------
P5-P-HABITAT-FRANCE_ARDOISE
P5-P-HABITAT-FRANCE_BRIQUE_TUILE

 ----------------------------------------------------------------------------------------------------
P7-I-BATIMENT DE SANTE-FRANCE_ARDOISE
P7-I-BATIMENT DE SANTE-FRANCE_TUILE

 ----------------------------------------------------------------------------------------------------
P3-I-BATIMENT DE SANTE-FRANCE_ARDOISE
P3-I-BATIMENT DE SANTE-FRANCE_TUILE

 ----------------------------------------------------------------------------------------------------
P1-P-HABITAT-FRANCE_PIERRE_GRES_ARDOISE
P1-P-HABITAT-FRANCE_PIERRE_GRES_TUILE

 ----------------------------------------------------------------------------------------------------
P2-I-BATIMENT DE SANTE-FRANCE_ARDOISE
P2-I-BATIMENT DE SANTE-FRANCE_TUILE

 ----------------------------------------------------------------------------------------------------
P1-I-CHATEAU-FRANCE_PIERRE_GRANITE_ARDOISE
P1-I-CHATEAU-FRANCE_PIERRE_GRANITE_TUILE

 ----------------------------------------------------------------------------------------------------
P1-I-CHATEAU-FRANCE_PIERRE_GRES_ARDOISE
P1-I-CHATEAU-FRANCE_PIERRE_GRES_TUILE

 ----------------------------------------------------------------------------------------------------
P1-I-HABITAT-FRANCE_PIERRE_GRES_ARDOISE
P1-I-HABITAT-FRANCE_PIERRE_GRES_TUILE

 ----------------------------------------------------------------------------------------------------
P5-I-HABITAT-FRANCE_ARDOISE
P5-I-HABITAT-FRANCE_TUILE

 ----------------------------------------------------------------------------------------------------
P1-BA-BATIMENT AGRICOLE-FRANCE_PIERRE_GRANITE_ARDOISE
P1-BA-BATIMENT AGRICOLE-FRANCE_PIERRE_GRANITE_TUILE

 ----------------------------------------------------------------------------------------------------
P1-P-HABITAT-FRANCE_BOIS_ARDOISE
P1-P-HABITAT-FRANCE_BOIS_TUILE

 ----------------------------------------------------------------------------------------------------
P5-I-BATIMENT D ENSEIGNEMENT-FRANCE_ARDOISE
P5-I-BATIMENT D ENSEIGNEMENT-FRANCE_TUILE

 ----------------------------------------------------------------------------------------------------
P1-P-HABITAT-FRANCE_PIERRE_CALCAIRE_TUILE
P1-P-HABITAT-FRANCE_PIERRE_CALCAIRE_ZINC

,TERRITOIRE,REVETEMENT_EXT3,EP_RE3,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,
HAB_P_P1_TCAL_TUI,FRANCE_PIERRE_CALCAIRE_TUILE,TUILE CANAL,$2.00,STRUCTURE BOIS,0,NON,0,NON,$0.00
HAB_P_P1_TCA_ZIN,FRANCE_PIERRE_CALCAIRE_ZINC,COUVERTURE ZINC,$1.00,STRUCTURE BOIS,0,NON,0,NON,$0.00

In [17]:
for group in three_ceilings:
    print('\n', "-"*100)
    for e in group:
        print(e)
    
    df0 = df[df["arch"]==group[0]]
    df1 = df[df["arch"]==group[1]]
    df2 = df[df["arch"]==group[2]]

    group_df = pd.concat([df0,df1,df2])[["TERRITOIRE",
                                    "REVETEMENT_EXT3",
                                    "EP_RE3",
                                    "PORTEUR3",
                                    "EP_PORTEUR3",
                                    "ISOLANT3",
                                    "EP_ISOLANT3",
                                    "REVETEMENT_INT3",
                                    "EP_RI3",
                                    ]]
    if (sum(group_df.iloc[0][2:] != group_df.iloc[1][2:]) + 
        sum(group_df.iloc[0][2:] != group_df.iloc[2][2:])
        +
        sum(group_df.iloc[1][2:] != group_df.iloc[2][2:])
           )!= 0:
        display(group_df)

 ----------------------------------------------------------------------------------------------------
P1-I-HABITAT-FRANCE_PIERRE_CALCAIRE_ARDOISE
P1-I-HABITAT-FRANCE_PIERRE_CALCAIRE_TUILE
P1-I-HABITAT-FRANCE_PIERRE_CALCAIRE_ZINC

,TERRITOIRE,REVETEMENT_EXT3,EP_RE3,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,
HAB_I_P1_TCAL_ARD,FRANCE_PIERRE_CALCAIRE_ARDOISE,ARDOISE,$2.00,STRUCTURE BOIS,0,NON,0,NON,$0.00
HAB_I_P1_TCAL_TUI,FRANCE_PIERRE_CALCAIRE_TUILE,TUILE PLATE,$2.00,STRUCTURE BOIS,0,NON,0,NON,$0.00
HAB_I_P1_TCA_ZIN,FRANCE_PIERRE_CALCAIRE_ZINC,COUVERTURE ZINC,$1.00,STRUCTURE BOIS,0,NON,0,NON,$0.00

 ----------------------------------------------------------------------------------------------------
P1-I-CHATEAU-FRANCE_PIERRE_CALCAIRE_ARDOISE
P1-I-CHATEAU-FRANCE_PIERRE_CALCAIRE_TUILE
P1-I-CHATEAU-FRANCE_PIERRE_CALCAIRE_ZINC

,TERRITOIRE,REVETEMENT_EXT3,EP_RE3,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,
CHA_I_P1_TCAL_ARD,FRANCE_PIERRE_CALCAIRE_ARDOISE,ARDOISE,$2.00,STRUCTURE BOIS,0,NON,0,NON,$0.00
CHA_I_P1_TCAL_TUI,FRANCE_PIERRE_CALCAIRE_TUILE,TUILE,$2.00,STRUCTURE BOIS,0,NON,0,NON,$0.00
CHA_I_P1_TCAL_ZIN,FRANCE_PIERRE_CALCAIRE_ZINC,COUVERTURE ZINC,$1.00,STRUCTURE BOIS,0,NON,0,NON,$0.00

 ----------------------------------------------------------------------------------------------------
P1-I-TERTIAIRE-FRANCE_PIERRE_CALCAIRE_ARDOISE
P1-I-TERTIAIRE-FRANCE_PIERRE_CALCAIRE_TUILE
P1-I-TERTIAIRE-FRANCE_PIERRE_CALCAIRE_ZINC

,TERRITOIRE,REVETEMENT_EXT3,EP_RE3,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,
TER_I_P1_TCAL_ARD,FRANCE_PIERRE_CALCAIRE_ARDOISE,ARDOISE,$2.00,STRUCTURE BOIS,0,NON,0,NON,$0.00
TER_I_P1_TCAL_TUI,FRANCE_PIERRE_CALCAIRE_TUILE,TUILE PLATE,$2.00,STRUCTURE BOIS,0,NON,0,NON,$0.00
TER_I_P1_TCA_ZIN,FRANCE_PIERRE_CALCAIRE_ZINC,COUVERTURE ZINC,$1.00,STRUCTURE BOIS,0,NON,0,NON,$0.00

### Conclusion
L'unique difference entre les caractéristiques des toits (à part révétement extérieur),
est sur l'epaisseur du revetement, uniquement pour les cas où il y a de la toiture zinc.

## Calculate roof U-value

### Check the archetypes per roof dispositif

In [75]:
for disp_t in df["DISPOSTIIF_TOIT_ OPTION1"].unique():
    print("\n",disp_t)
    display(df[df["DISPOSTIIF_TOIT_ OPTION1"]==disp_t][["TERRITOIRE", 
                                                        "PERIODE",
                                                        "PORTEUR3",
                                                        "EP_PORTEUR3",
                                                        "ISOLANT3",
                                                        "EP_ISOLANT3",
                                                        "REVETEMENT_EXT3",
                                                        "EP_RE3",
                                                        "REVETEMENT_INT3",
                                                        "EP_RI3",
                                                        ]])

 HAB_T_P1_TBR_TU

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
AGR_BA_P1_TBR_TF,FRANCE,P1,STRUCTURE BOIS,0,NON,0,TUILE,$2.00,NON,$0.00
AGR_BA_P1_TBR_TUI,FRANCE_BRIQUE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE,$2.00,NON,$0.00
IND_BA_P1_TF,FRANCE,P1,STRUCTURE BOIS,0,NON,0,TUILE,$2.00,NON,$0.00
IND_BA_P1_TBR_TUI,FRANCE_BRIQUE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE,$2.00,NON,$0.00
SAN_I_P1_TF,FRANCE,P1,STRUCTURE BOIS,0,NON,0,TUILE,$2.00,NON,$0.00
SAN_I_P1_TBR_TUI,FRANCE_BRIQUE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE,$2.00,NON,$0.00
REL_I_P1_TBR_TUI,FRANCE_BRIQUE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE,$2.00,NON,$0.00
REL_I_P1_TSCH_TUI,FRANCE_PIERRE_SCHISTE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE,$2.00,NON,$0.00
CHA_I_P1_TCAL_TUI,FRANCE_PIERRE_CALCAIRE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE,$2.00,NON,$0.00
COM_I_P1_TF,FRANCE,P1,STRUCTURE BOIS,0,NON,0,TUILE,$2.00,NON,$0.00
HAB_I_P1_TF,FRANCE,P1,STRUCTURE BOIS,0,NON,0,TUILE,$2.00,NON,$0.00
TER_I_P1_TF,FRANCE,P1,STRUCTURE BOIS,0,NON,0,TUILE,$2.00,NON,$0.00
HAB_P_P1_TGRE_TUI,FRANCE_PIERRE_GRES_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE,$2.00,NON,$0.00
LNC_P_P1_TF,FRANCE,P1,STRUCTURE BOIS,0,NON,0,TUILE,$2.00,NON,$0.00
LNC_P_P2_TF,FRANCE,P2,STRUCTURE BOIS,0,NON,0,TUILE,$2.00,NON,$0.00
LNC_P_P3_TF,FRANCE,P3,STRUCTURE BOIS,0,NON,0,TUILE,$2.00,NON,$0.00
LNC_P_P4_TF,FRANCE,P4,STRUCTURE BOIS,0,NON,0,TUILE,$2.00,NON,$0.00
LNC_P_P5_TF,FRANCE,P5,STRUCTURE BOIS,0,NON,0,TUILE,$2.00,NON,$0.00
LNC_P_P6_TF,FRANCE,P6,STRUCTURE BOIS,0,NON,0,TUILE,$2.00,NON,$0.00
LNC_P_P7_TF,FRANCE,P7,STRUCTURE BOIS,0,NON,0,TUILE,$2.00,NON,$0.00

 HAB_T_P1_TPI_AR

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
AGR_BA_P1_TBO_ARD,FRANCE_BOIS_ARDOISE,P1,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
AGR_BA_P1_TCAL_ARD,FRANCE_PIERRE_CALCAIRE_ARDOISE,P1,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
AGR_BA_P1_TGRA_ARD,FRANCE_PIERRE_GRANITE_ARDOISE,P1,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
AGR_BA_P1_TGRE_ARD,FRANCE_PIERRE_GRES_ARDOISE,P1,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
AGR_BA_P1_TVOL_ARD,FRANCE_PIERRE_VOLCANIQUE_ARDOISE,P1,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
SCO_I_P1_TF,FRANCE,P1,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
SAN_I_P1_TAR,FRANCE_PIERRE_ARDOISE,P1,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
REL_I_P1_TVOL_ARD,FRANCE,P1,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
REL_I_P1_TF,FRANCE_PIERRE_ARDOISE,P1,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
CHA_I_P1_TF,FRANCE,P1,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
CHA_I_P1_TCAL_ARD,FRANCE_PIERRE_CALCAIRE_ARDOISE,P1,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
CHA_I_P1_TGRA_ARD,FRANCE_PIERRE_GRANITE_ARDOISE,P1,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
CHA_I_P1_TGRE_ARD,FRANCE_PIERRE_GRES_ARDOISE,P1,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
CHA_I_P1_TVOL_ARD,FRANCE_PIERRE_VOLCANIQUE_ARDOISE,P1,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
HAB_I_P1_TBO_ARD,FRANCE_BOIS_ARDOISE,P1,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
HAB_I_P1_TCAL_ARD,FRANCE_PIERRE_CALCAIRE_ARDOISE,P1,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
HAB_I_P1_TGRA_ARD,FRANCE_PIERRE_GRANITE_ARDOISE,P1,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
HAB_I_P1_TGRE_ARD,FRANCE_PIERRE_GRES_ARDOISE,P1,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
HAB_I_P1_TVOL_ARD,FRANCE_PIERRE_VOLCANIQUE_ARDOISE,P1,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
TER_I_P1_TBO_ARD,FRANCE_BOIS_ARDOISE,P1,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
TER_I_P1_TCAL_ARD,FRANCE_PIERRE_CALCAIRE_ARDOISE,P1,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
TER_I_P1_TGRA_ARD,FRANCE_PIERRE_GRANITE_ARDOISE,P1,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
TER_I_P1_TGRE_ARD,FRANCE_PIERRE_GRES_ARDOISE,P1,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
TER_I_P1_TVOL_ARD,FRANCE_PIERRE_VOLCANIQUE_ARDOISE,P1,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
HAB_P_P1_TCAL_ARD,FRANCE,P1,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
HAB_P_P1_TBO_ARD,FRANCE_BOIS_ARDOISE,P1,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
HAB_P_P1_TGRA_ARD,FRANCE_PIERRE_GRANITE_ARDOISE,P1,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
HAB_P_P1_TGRE_ARD,FRANCE_PIERRE_GRES_ARDOISE,P1,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00

 HAB_T_P1_TBR_TM

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
AGR_BA_P1_TBO_TUI,FRANCE_BOIS_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE MECANIQUE,$2.00,NON,$0.00
HAB_I_P1_TBO_TUI,FRANCE_BOIS_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE MECANIQUE,$2.00,NON,$0.00
TER_I_P1_TBO_TUI,FRANCE_BOIS_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE MECANIQUE,$2.00,NON,$0.00

 HAB_T_P1_TBR_TP

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
AGR_BA_P1_TCAL_TUI,FRANCE_PIERRE_CALCAIRE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE PLATE,$2.00,NON,$0.00
AGR_BA_P1_TGRA_TUI,FRANCE_PIERRE_GRANITE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE PLATE,$2.00,NON,$0.00
AGR_BA_P1_TGRE_TUI,FRANCE_PIERRE_GRES_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE PLATE,$2.00,NON,$0.00
AGR_BA_P1_TMEU,FRANCE_PIERRE_MEULIERE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE PLATE,$2.00,NON,$0.00
AGR_BA_P1_TSCH_TUI,FRANCE_PIERRE_SCHISTE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE PLATE,$2.00,NON,$0.00
AGR_BA_P1_TER_TUI,FRANCE_TERRE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE PLATE,$2.00,NON,$0.00
CHA_I_P1_TGAL_TUI,FRANCE_PIERRE_GALET_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE PLATE,$2.00,NON,$0.00
CHA_I_P1_TGRE_TUI,FRANCE_PIERRE_GRES_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE PLATE,$2.00,NON,$0.00
CHA_I_P1_TSCH_TUI,FRANCE_PIERRE_SCHISTE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE PLATE,$2.00,NON,$0.00
CHA_I_P1_TER_TUI,FRANCE_TERRE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE PLATE,$2.00,NON,$0.00
HAB_I_P1_TCAL_TUI,FRANCE_PIERRE_CALCAIRE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE PLATE,$2.00,NON,$0.00
HAB_I_P1_TGRA_TUI,FRANCE_PIERRE_GRANITE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE PLATE,$2.00,NON,$0.00
HAB_I_P1_TGRE_TUI,FRANCE_PIERRE_GRES_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE PLATE,$2.00,NON,$0.00
HAB_I_P1_TMEU,FRANCE_PIERRE_MEULIERE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE PLATE,$2.00,NON,$0.00
HAB_I_P1_TSCH_TUI,FRANCE_PIERRE_SCHISTE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE PLATE,$2.00,NON,$0.00
TER_I_P1_TCAL_TUI,FRANCE_PIERRE_CALCAIRE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE PLATE,$2.00,NON,$0.00
TER_I_P1_TGRA_TUI,FRANCE_PIERRE_GRANITE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE PLATE,$2.00,NON,$0.00
TER_I_P1_TGRE_TUI,FRANCE_PIERRE_GRES_ARDOISE,P1,STRUCTURE BOIS,0,NON,0,TUILE PLATE,$2.00,NON,$0.00
TER_I_P1_TMEU,FRANCE_PIERRE_MEULIERE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE PLATE,$2.00,NON,$0.00
TER_I_P1_TSCH_TUI,FRANCE_PIERRE_SCHISTE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE PLATE,$2.00,NON,$0.00
HAB_P_P1_TBO_TUI,FRANCE_BOIS_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE PLATE,$2.00,NON,$0.00
HAB_P_P1_TGRA_TUI,FRANCE_PIERRE_GRANITE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE PLATE,$2.00,NON,$0.00
HAB_P_P1_TMEU,FRANCE_PIERRE_MEULIERE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE PLATE,$2.00,NON,$0.00
HAB_P_P1_TSCH_TUI,FRANCE_PIERRE_SCHISTE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE PLATE,$2.00,NON,$0.00

 HAB_T_P1_TBR_TC

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
AGR_BA_P1_TGAL_TUI,FRANCE_PIERRE_GALET_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE CANAL,$2.00,NON,$0.00
AGR_BA_P1_TGNE,FRANCE_PIERRE_GNEISS_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE CANAL,$2.00,NON,$0.00
CHA_I_P1_TBR_TUI,FRANCE_BRIQUE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE CANAL,$2.00,NON,$0.00
CHA_I_P1_TGRA_TUI,FRANCE_PIERRE_GRANITE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE CANAL,$2.00,NON,$0.00
HAB_I_P1_TBR_TUI,FRANCE_BRIQUE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE CANAL,$2.00,NON,$0.00
HAB_I_P1_TGAL_TUI,FRANCE_PIERRE_GALET_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE CANAL,$2.00,NON,$0.00
TER_I_P1_TBR_TUI,FRANCE_BRIQUE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE CANAL,$2.00,NON,$0.00
TER_I_P1_TGAL_TUI,FRANCE_PIERRE_GALET_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE CANAL,$2.00,NON,$0.00
HAB_P_P1_TBR_TUI,FRANCE_BRIQUE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE CANAL,$2.00,NON,$0.00
HAB_P_P1_TCAL_TUI,FRANCE_PIERRE_CALCAIRE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE CANAL,$2.00,NON,$0.00
HAB_P_P1_TGAL_TUI,FRANCE_PIERRE_GALET_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE CANAL,$2.00,NON,$0.00
HAB_P_P2_TF,FRANCE,P2,STRUCTURE BOIS,0,NON,0,TUILE CANAL,$2.00,NON,$0.00
HAB_P_P2_TBR,FRANCE_BRIQUE_TUILE,P2,STRUCTURE BOIS,0,NON,0,TUILE CANAL,$2.00,NON,$0.00

 SER_T_P1_TN

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
SER_BA_P1_TF,FRANCE,P1,STRUCTURE METAL,0,NON,0,SIMPLE VITRAGE,$2.00,NON,$0.00

 CHA_T_P1_TZINC

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
CHA_I_P1_TCAL_ZIN,FRANCE_PIERRE_CALCAIRE_ZINC,P1,STRUCTURE BOIS,0,NON,0,COUVERTURE ZINC,$1.00,NON,$0.00
HAB_I_P1_TCA_ZIN,FRANCE_PIERRE_CALCAIRE_ZINC,P1,STRUCTURE BOIS,0,NON,0,COUVERTURE ZINC,$1.00,NON,$0.00
TER_I_P1_TCA_ZIN,FRANCE_PIERRE_CALCAIRE_ZINC,P1,STRUCTURE BOIS,0,NON,0,COUVERTURE ZINC,$1.00,NON,$0.00
HAB_P_P1_TCA_ZIN,FRANCE_PIERRE_CALCAIRE_ZINC,P1,STRUCTURE BOIS,0,NON,0,COUVERTURE ZINC,$1.00,NON,$0.00

 HAB_T_P1_TBR_TR

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
HAB_I_P1_TER_TUI,FRANCE_TERRE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE ROMAINE,$2.00,NON,$0.00
TER_I_P1_TER_TUI,FRANCE_TERRE_TUILE,P1,STRUCTURE BOIS,0,NON,0,TUILE ROMAINE,$2.00,NON,$0.00

 HAB_T_P4_TPI_AR

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
HAB_P_P1_TVOL_ARD,FRANCE_PIERRE_VOLCANIQUE_ARDOISE,P1,STRUCTURE BOIS,0,ITI_LM,12,ARDOISE,$2.00,PLAQUE DE PLATRE,$1.30
SCO_I_P4_TAR,FRANCE_ARDOISE,P4,STRUCTURE BOIS,0,ITI_LM,12,ARDOISE,$2.00,PLAQUE DE PLATRE,$1.30
SAN_I_P4_TAR,FRANCE_ARDOISE,P4,STRUCTURE BOIS,0,ITI_LM,12,ARDOISE,$2.00,PLAQUE DE PLATRE,$1.30
HAB_I_P4_TAR,FRANCE_ARDOISE,P4,STRUCTURE BOIS,0,ITI_LM,12,ARDOISE,$2.00,PLAQUE DE PLATRE,$1.30
HAB_P_P4_TAR,FRANCE_ARDOISE,P4,STRUCTURE BOIS,0,ITI_LM,12,ARDOISE,$2.00,PLAQUE DE PLATRE,$1.30

 TER_T_P2_TN_BAC

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
AGR_BA_P2_TF,FRANCE,P2,STRUCTURE METAL,0,NON,0,TOLE,$0.80,NON,$0.00
IND_BA_P2_TF,FRANCE,P2,STRUCTURE METAL,0,NON,0,TOLE,$0.80,NON,$0.00
SPO_BA_P2_TF,FRANCE,P2,STRUCTURE METAL,0,NON,0,TOLE,$0.80,NON,$0.00
BA_LNC_P7_TF,FRANCE,P7,STRUCTURE METAL,0,NON,0,TOLE,$0.80,NON,$0.00

 SER_T_P2_TN

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
SER_BA_P2_TF,FRANCE,P2,STRUCTURE METAL,0,NON,0,SIMPLE VITRAGE,$2.00,NON,$0.00

 HAB_T_P2_TBR_TC

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
SCO_I_P2_TF,FRANCE,P2,STRUCTURE BOIS,0,NON,0,TUILE CANAL,$2.00,NON,$0.00
SCO_I_P2_TBR,FRANCE_TUILE,P2,STRUCTURE BOIS,0,NON,0,TUILE CANAL,$2.00,NON,$0.00
SAN_I_P2_TF,FRANCE,P2,STRUCTURE BOIS,0,NON,0,TUILE CANAL,$2.00,NON,$0.00
SAN_I_P2_TBR,FRANCE_TUILE,P2,STRUCTURE BOIS,0,NON,0,TUILE CANAL,$2.00,NON,$0.00
HAB_I_P2_TF,FRANCE,P2,STRUCTURE BOIS,0,NON,0,TUILE CANAL,$2.00,NON,$0.00
HAB_I_P2_TBR,FRANCE_TUILE,P2,STRUCTURE BOIS,0,NON,0,TUILE CANAL,$2.00,NON,$0.00

 HAB_T_P2_TPI_AR

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
SCO_I_P2_TAR,FRANCE_ARDOISE,P2,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
SAN_I_P2_TAR,FRANCE_ARDOISE,P2,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
HAB_I_P2_TAR,FRANCE_ARDOISE,P2,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
HAB_P_P2_TAR,FRANCE_ARDOISE,P2,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00

 HAB_T_P2_TN_GR

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
REL_I_P2_TF,FRANCE,P2,DALLE BETON,20,NON,0,GRAVIER,$5.00,NON,$0.00
COM_I_P2_TF,FRANCE,P2,DALLE BETON,20,NON,0,GRAVIER,$5.00,NON,$0.00
TER_I_P2_TF,FRANCE,P2,DALLE BETON,20,NON,0,GRAVIER,$5.00,NON,$0.00
HAB_IGH_P2_TF,FRANCE,P2,DALLE BETON,20,NON,0,GRAVIER,$5.00,NON,$0.00

 TER_T_P3_TN_BAC

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
AGR_BA_P3_TF,FRANCE,P3,STRUCTURE METAL,0,NON,0,TOLE,$0.80,NON,$0.00
IND_BA_P3_TF,FRANCE,P3,STRUCTURE METAL,0,NON,0,TOLE,$0.80,NON,$0.00
SPO_BA_P3_TF,FRANCE,P3,STRUCTURE METAL,0,NON,0,TOLE,$0.80,NON,$0.00

 SER_T_P3_TN

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
SER_BA_P3_TF,FRANCE,P3,STRUCTURE METAL,0,NON,0,SIMPLE VITRAGE,$2.00,NON,$0.00

 HAB_T_P3_TN_TU

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
SCO_I_P3_TF,FRANCE,P3,STRUCTURE BOIS,0,NON,0,TUILE,$2.00,NON,$0.00
SCO_I_P3_TBR,FRANCE_TUILE,P3,STRUCTURE BOIS,0,NON,0,TUILE,$2.00,NON,$0.00
SAN_I_P3_TF,FRANCE,P3,STRUCTURE BOIS,0,NON,0,TUILE,$2.00,NON,$0.00
SAN_I_P3_TBR,FRANCE_TUILE,P3,STRUCTURE BOIS,0,NON,0,TUILE,$2.00,NON,$0.00
HAB_I_P3_TF,FRANCE,P3,STRUCTURE BOIS,0,NON,0,TUILE,$2.00,NON,$0.00
HAB_I_P3_TBR,FRANCE_TUILE,P3,STRUCTURE BOIS,0,NON,0,TUILE,$2.00,NON,$0.00
HAB_P_P3_TF,FRANCE,P3,STRUCTURE BOIS,0,NON,0,TUILE,$2.00,NON,$0.00
HAB_P_P3_TBR,FRANCE_BRIQUE_TUILE,P3,STRUCTURE BOIS,0,NON,0,TUILE,$2.00,NON,$0.00

 HAB_T_P3_TPI_AR

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
SCO_I_P3_TAR,FRANCE_ARDOISE,P3,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
SAN_I_P3_TAR,FRANCE_ARDOISE,P3,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
HAB_I_P3_TAR,FRANCE_ARDOISE,P3,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00
HAB_P_P3_TAR,FRANCE_ARDOISE,P3,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00

 HAB_T_P3_TN_GR

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
REL_I_P3_TF,FRANCE,P3,DALLE BETON,20,NON,0,GRAVIER,$5.00,NON,$0.00
COM_I_P3_TF,FRANCE,P3,DALLE BETON,20,NON,0,GRAVIER,$5.00,NON,$0.00
TER_I_P3_TF,FRANCE,P3,DALLE BETON,20,NON,0,GRAVIER,$5.00,NON,$0.00
HAB_IGH_P3_TF,FRANCE,P3,DALLE BETON,20,NON,0,GRAVIER,$5.00,NON,$0.00

 TER_T_P4_TN_BAC

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
AGR_BA_P4_TF,FRANCE,P4,STRUCTURE METAL,0,ITI_LM,5,TOLE,$0.80,NON,$0.00
IND_BA_P4_TF,FRANCE,P4,STRUCTURE METAL,0,ITI_LM,5,TOLE,$0.80,NON,$0.00
SPO_BA_P4_TF,FRANCE,P4,STRUCTURE METAL,0,ITI_LM,5,TOLE,$0.80,NON,$0.00
COM_BA_P4_TF,FRANCE,P4,STRUCTURE METAL,0,ITI_LM,5,TOLE,$0.80,NON,$0.00

 SER_T_P4_TN

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
SER_BA_P4_TF,FRANCE,P4,STRUCTURE METAL,0,NON,0,SIMPLE VITRAGE,$2.00,NON,$0.00

 HAB_T_P4_TN_TU

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
SCO_I_P4_TF,FRANCE,P4,STRUCTURE BOIS,0,ITI_LM,12,TUILE,$2.00,PLAQUE DE PLATRE,$1.30
SCO_I_P4_TBR,FRANCE_TUILE,P4,STRUCTURE BOIS,0,ITI_LM,12,TUILE,$2.00,PLAQUE DE PLATRE,$1.30
SAN_I_P4_TF,FRANCE,P4,STRUCTURE BOIS,0,ITI_LM,12,TUILE,$2.00,PLAQUE DE PLATRE,$1.30
SAN_I_P4_TBR,FRANCE_TUILE,P4,STRUCTURE BOIS,0,ITI_LM,12,TUILE,$2.00,PLAQUE DE PLATRE,$1.30
HAB_I_P4_TF,FRANCE,P4,STRUCTURE BOIS,0,ITI_LM,12,TUILE,$2.00,PLAQUE DE PLATRE,$1.30
HAB_I_P4_TBR,FRANCE_TUILE,P4,STRUCTURE BOIS,0,ITI_LM,12,TUILE,$2.00,PLAQUE DE PLATRE,$1.30
HAB_P_P4_TF,FRANCE,P4,STRUCTURE BOIS,0,ITI_LM,12,TUILE,$2.00,PLAQUE DE PLATRE,$1.30
HAB_P_P4_TBR,FRANCE_BRIQUE_TUILE,P4,STRUCTURE BOIS,0,ITI_LM,12,TUILE,$2.00,PLAQUE DE PLATRE,$1.30

 HAB_T_P4_TN_GR

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
REL_I_P4_TF,FRANCE,P4,DALLE BETON,20,ITI_LM,12,GRAVIER,$5.00,PLAQUE DE PLATRE,$1.30
COM_I_P4_TF,FRANCE,P4,DALLE BETON,20,ITI_LM,12,GRAVIER,$5.00,PLAQUE DE PLATRE,$1.30
TER_I_P4_TF,FRANCE,P4,DALLE BETON,20,ITI_LM,12,GRAVIER,$5.00,PLAQUE DE PLATRE,$1.30
HAB_IGH_P4_TF,FRANCE,P4,DALLE BETON,20,ITI_LM,12,GRAVIER,$5.00,PLAQUE DE PLATRE,$1.30
TER_IGH_P4_TF,FRANCE,P4,DALLE BETON,20,ITI_LM,12,GRAVIER,$5.00,PLAQUE DE PLATRE,$1.30

 TER_T_P5_TN_BAC

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
AGR_BA_P5_TF,FRANCE,P5,STRUCTURE METAL,0,ITI_LM,9,TOLE,$0.80,NON,$0.00
IND_BA_P5_TF,FRANCE,P5,STRUCTURE METAL,0,ITI_LM,9,TOLE,$0.80,NON,$0.00
SPO_BA_P5_TF,FRANCE,P5,STRUCTURE METAL,0,ITI_LM,9,TOLE,$0.80,NON,$0.00
COM_BA_P5_TF,FRANCE,P5,STRUCTURE METAL,0,ITI_LM,9,TOLE,$0.80,NON,$0.00

 SER_T_P5_TN

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
SER_BA_P5_TF,FRANCE,P5,STRUCTURE METAL,0,NON,0,DOUBLE VITRAGE,$3.00,NON,$0.00

 HAB_T_P5_TN_TU

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
SCO_I_P5_TF,FRANCE,P5,STRUCTURE BOIS,0,ITI_LM,15,TUILE,$2.00,PLAQUE DE PLATRE,$1.30
SCO_I_P5_TBR,FRANCE_TUILE,P5,STRUCTURE BOIS,0,ITI_LM,15,TUILE,$2.00,PLAQUE DE PLATRE,$1.30
SAN_I_P5_TF,FRANCE,P5,STRUCTURE BOIS,0,ITI_LM,15,TUILE,$2.00,PLAQUE DE PLATRE,$1.30
SAN_I_P5_TBR,FRANCE_TUILE,P5,STRUCTURE BOIS,0,ITI_LM,15,TUILE,$2.00,PLAQUE DE PLATRE,$1.30
HAB_I_P5_TF,FRANCE,P5,STRUCTURE BOIS,0,ITI_LM,15,TUILE,$2.00,PLAQUE DE PLATRE,$1.30
HAB_I_P5_TBR,FRANCE_TUILE,P5,STRUCTURE BOIS,0,ITI_LM,15,TUILE,$2.00,PLAQUE DE PLATRE,$1.30
HAB_P_P5_TF,FRANCE,P5,STRUCTURE BOIS,0,ITI_LM,15,TUILE,$2.00,PLAQUE DE PLATRE,$1.30
HAB_P_P5_TBR,FRANCE_BRIQUE_TUILE,P5,STRUCTURE BOIS,0,ITI_LM,15,TUILE,$2.00,PLAQUE DE PLATRE,$1.30

 HAB_T_P5_TPI_AR

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
SCO_I_P5_TAR,FRANCE_ARDOISE,P5,STRUCTURE BOIS,0,ITI_LM,15,ARDOISE,$2.00,PLAQUE DE PLATRE,$1.30
SAN_I_P5_TAR,FRANCE_ARDOISE,P5,STRUCTURE BOIS,0,ITI_LM,15,ARDOISE,$2.00,PLAQUE DE PLATRE,$1.30
HAB_I_P5_TAR,FRANCE_ARDOISE,P5,STRUCTURE BOIS,0,ITI_LM,15,ARDOISE,$2.00,PLAQUE DE PLATRE,$1.30
HAB_P_P5_TAR,FRANCE_ARDOISE,P5,STRUCTURE BOIS,0,ITI_LM,15,ARDOISE,$2.00,PLAQUE DE PLATRE,$1.30

 HAB_T_P5_TN_GR

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
REL_I_P5_TF,FRANCE,P5,DALLE BETON,20,ITI_LM,15,GRAVIER,$5.00,PLAQUE DE PLATRE,$1.30
COM_I_P5_TF,FRANCE,P5,DALLE BETON,20,ITI_LM,15,GRAVIER,$5.00,PLAQUE DE PLATRE,$1.30
TER_I_P5_TF,FRANCE,P5,DALLE BETON,20,ITI_LM,15,GRAVIER,$5.00,PLAQUE DE PLATRE,$1.30
HAB_IGH_P5_TF,FRANCE,P5,DALLE BETON,20,ITI_LM,15,GRAVIER,$5.00,PLAQUE DE PLATRE,$1.30
TER_IGH_P5_TF,FRANCE,P5,DALLE BETON,20,ITI_LM,15,GRAVIER,$5.00,PLAQUE DE PLATRE,$1.30

 TER_T_P6_TN_BAC

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
AGR_BA_P6_TF,FRANCE,P6,STRUCTURE METAL,0,ITI_LM,11,TOLE,$0.80,NON,$0.00
IND_BA_P6_TF,FRANCE,P6,STRUCTURE METAL,0,ITI_LM,11,TOLE,$0.80,NON,$0.00
SPO_BA_P6_TF,FRANCE,P6,STRUCTURE METAL,0,ITI_LM,11,TOLE,$0.80,NON,$0.00
COM_BA_P6_TF,FRANCE,P6,STRUCTURE METAL,0,ITI_LM,11,TOLE,$0.80,NON,$0.00
TER_I_P6_TF,FRANCE,P6,STRUCTURE METAL,0,ITI_LM,11,TOLE,$0.80,NON,$0.00

 SER_T_P6_TN

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
SER_BA_P6_TF,FRANCE,P6,STRUCTURE METAL,0,NON,0,DOUBLE VITRAGE,$3.00,NON,$0.00

 HAB_T_P6_TN_TU

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
SCO_I_P6_TF,FRANCE,P6,STRUCTURE BOIS,0,ITI_LM,20,TUILE,$2.00,PLAQUE DE PLATRE,$1.30
SCO_I_P6_TBR,FRANCE_TUILE,P6,STRUCTURE BOIS,0,ITI_LM,20,TUILE,$2.00,PLAQUE DE PLATRE,$1.30
SAN_I_P6_TF,FRANCE,P6,STRUCTURE BOIS,0,ITI_LM,20,TUILE,$2.00,PLAQUE DE PLATRE,$1.30
SAN_I_P6_TBR,FRANCE_TUILE,P6,STRUCTURE BOIS,0,ITI_LM,20,TUILE,$2.00,PLAQUE DE PLATRE,$1.30
HAB_I_P6_TF,FRANCE,P6,STRUCTURE BOIS,0,ITI_LM,20,TUILE,$2.00,PLAQUE DE PLATRE,$1.30
HAB_I_P6_TBR,FRANCE_TUILE,P6,STRUCTURE BOIS,0,ITI_LM,20,TUILE,$2.00,PLAQUE DE PLATRE,$1.30
HAB_P_P6_TF,FRANCE,P6,STRUCTURE BOIS,0,ITI_LM,20,TUILE,$2.00,PLAQUE DE PLATRE,$1.30
HAB_P_P6_TBR,FRANCE_BRIQUE_TUILE,P6,STRUCTURE BOIS,0,ITI_LM,20,TUILE,$2.00,PLAQUE DE PLATRE,$1.30

 HAB_T_P6_TPI_AR

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
SCO_I_P6_TAR,FRANCE_ARDOISE,P6,STRUCTURE BOIS,0,ITI_LM,20,ARDOISE,$2.00,PLAQUE DE PLATRE,$1.30
SAN_I_P6_TAR,FRANCE_ARDOISE,P6,STRUCTURE BOIS,0,ITI_LM,20,ARDOISE,$2.00,PLAQUE DE PLATRE,$1.30
HAB_I_P6_TAR,FRANCE_ARDOISE,P6,STRUCTURE BOIS,0,ITI_LM,20,ARDOISE,$2.00,PLAQUE DE PLATRE,$1.30
HAB_P_P6_TAR,FRANCE_ARDOISE,P6,STRUCTURE BOIS,0,ITI_LM,20,ARDOISE,$2.00,PLAQUE DE PLATRE,$1.30

 HAB_T_P6_TN_GR

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
REL_I_P6_TF,FRANCE,P6,DALLE BETON,20,ITI_LM,20,GRAVIER,$5.00,PLAQUE DE PLATRE,$1.30
COM_I_P6_TF,FRANCE,P6,DALLE BETON,20,ITI_LM,20,GRAVIER,$5.00,PLAQUE DE PLATRE,$1.30
HAB_IGH_P6_TF,FRANCE,P6,DALLE BETON,20,ITI_LM,20,GRAVIER,$5.00,PLAQUE DE PLATRE,$1.30
TER_IGH_P6_TF,FRANCE,P6,DALLE BETON,20,ITI_LM,20,GRAVIER,$5.00,PLAQUE DE PLATRE,$1.30

 TER_T_P7_TN_BAC

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
AGR_BA_P7_TF,FRANCE,P7,STRUCTURE METAL,0,ITI_LM,14,TOLE,$0.80,NON,$0.00
IND_BA_P7_TF,FRANCE,P7,STRUCTURE METAL,0,ITI_LM,14,TOLE,$0.80,NON,$0.00
SPO_BA_P7_TF,FRANCE,P7,STRUCTURE METAL,0,ITI_LM,14,TOLE,$0.80,NON,$0.00
COM_BA_P7_TF,FRANCE,P7,STRUCTURE METAL,0,ITI_LM,14,TOLE,$0.80,NON,$0.00

 SER_T_P7_TN

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
SER_BA_P7_TF,FRANCE,P7,STRUCTURE METAL,0,NON,0,DOUBLE VITRAGE,$3.00,NON,$0.00

 HAB_T_P7_TBR_TC

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
SCO_I_P7_TF,FRANCE,P7,STRUCTURE BOIS,0,ITI_LM,30,TUILE,$2.00,PLAQUE DE PLATRE,$1.30
SCO_I_P7_TBR,FRANCE_TUILE,P7,STRUCTURE BOIS,0,ITI_LM,30,TUILE,$2.00,PLAQUE DE PLATRE,$1.30
SAN_I_P7_TF,FRANCE,P7,STRUCTURE BOIS,0,ITI_LM,30,TUILE,$2.00,PLAQUE DE PLATRE,$1.30
SAN_I_P7_TBR,FRANCE_TUILE,P7,STRUCTURE BOIS,0,ITI_LM,30,TUILE,$2.00,PLAQUE DE PLATRE,$1.30
HAB_I_P7_TF,FRANCE,P7,STRUCTURE BOIS,0,ITI_LM,30,TUILE,$2.00,PLAQUE DE PLATRE,$1.30
HAB_I_P7_TAR,FRANCE_TUILE,P7,STRUCTURE BOIS,0,ITI_LM,30,TUILE,$2.00,PLAQUE DE PLATRE,$1.30
HAB_P_P7_TF,FRANCE,P7,STRUCTURE BOIS,0,ITI_LM,30,TUILE,$2.00,PLAQUE DE PLATRE,$1.30
HAB_P_P7_TBR,FRANCE_BRIQUE_TUILE,P7,STRUCTURE BOIS,0,ITI_LM,30,TUILE,$2.00,PLAQUE DE PLATRE,$1.30

 HAB_T_P7_TPI_AR

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
SCO_I_P7_TAR,FRANCE_ARDOISE,P7,STRUCTURE BOIS,0,ITI_LM,30,ARDOISE,$2.00,PLAQUE DE PLATRE,$1.30
SAN_I_P7_TAR,FRANCE_ARDOISE,P7,STRUCTURE BOIS,0,ITI_LM,30,ARDOISE,$2.00,PLAQUE DE PLATRE,$1.30
HAB_I_P7_TBR,FRANCE_ARDOISE,P7,STRUCTURE BOIS,0,ITI_LM,30,ARDOISE,$2.00,PLAQUE DE PLATRE,$1.30
HAB_P_P7_TAR,FRANCE_ARDOISE,P7,STRUCTURE BOIS,0,ITI_LM,30,ARDOISE,$2.00,PLAQUE DE PLATRE,$1.30

 HAB_T_P7_TN

,TERRITOIRE,PERIODE,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
NUMERO_TYPOLOGIE,,,,,,,,,,
REL_I_P7_TF,FRANCE,P7,DALLE BETON,20,ITE_POL,30,GRAVIER,$10.00,NON,$0.00
COM_I_P7_TF,FRANCE,P7,DALLE BETON,20,ITE_POL,30,GRAVIER,$10.00,NON,$0.00
TER_I_P7_TF,FRANCE,P7,DALLE BETON,20,ITE_POL,30,GRAVIER,$10.00,NON,$0.00
HAB_IGH_P7_TF,FRANCE,P7,DALLE BETON,20,ITE_POL,30,GRAVIER,$10.00,NON,$0.00
TER_IGH_P7_TF,FRANCE,P7,DALLE BETON,20,ITE_POL,30,GRAVIER,$10.00,NON,$0.00

#### Problems found with dates

**Dispositif toit -  archetype**
- TER_T_P2_TN_BAC 
        - BA_LNC_P7_TF  (not a problem since not analysing LNC)

- HAB_T_P1_TBR_TC 
        - HAB_P_P2_TF 
        - HAB_P_P2_TBR 	(both will be exceptions if we chose to define the U from the construction dates)
    
- **HAB_T_P4_TPI_AR**
        - HAB_P_P1_TVOL_ARD (an error I think, the dispositif should be HAB_T_P1_TPI_AR instead)
    
- HAB_T_P1_TBR_TU 
        - Local from all periods (not a problem since not analysing LNC)

In [87]:
# I think this is an error in Danube
df.loc["HAB_P_P1_TVOL_ARD"].EP_ISOLANT3

12

In [86]:
df.loc["HAB_P_P2_TF"]

PERIODE                                             P2
NOM_TYPOLOGIE                                        P
USAGE                                          HABITAT
TERRITOIRE                                      FRANCE
COMPACITE                                    TRES FORT
COUVERTURE_ROUTE                               ASPHALT
DATES                                      1949 - 1973
DATE_DEBUT                                        1949
DATE_FIN                                          1973
DISPOSITIF                              PAV_M_P2_TN_BC
DISPOSITIF1                             PAV_M_P2_TN_PA
DISPOSITIF2                                         ND
DISPOSITIF3                            HAB_T_P1_TBR_TC
DISPOSITIF4                                         ND
DISPOSITIF_MUR_OPTION1                  PAV_M_P2_TN_BC
DISPOSITIF_MUR_OPTION2                  PAV_M_P2_TN_PA
DISPOSITIF_MUR_OPTION3                              ND
DISPOSITIF_TOIT_OPTION2                             ND
DISPOSTIIF_TOIT_ OPTION1               HAB_T_P1_TBR_TC
EP_ISOLANT                                           0
EP_ISOLANT1                                          0
EP_ISOLANT2                                          0
EP_ISOLANT3                                          0
EP_ISOLANT4                                          0
EP_PLANCHER_INTER                                    0
EP_PLANCHER_RDC                                     20
EP_PORTEUR                                          20
EP_PORTEUR1                                         20
EP_PORTEUR2                                          0
EP_PORTEUR3                                          0
EP_PORTEUR4                                          0
EP_RE                                                2
EP_RE1                                               2
EP_RE2                                               0
EP_RE3                                           $2.00
EP_RE4                                               0
EP_RI                                            $1.00
EP_RI1                                           $1.30
EP_RI2                                           $0.00
EP_RI3                                           $0.00
EP_RI4                                           $0.00
ID_PLANCHER                 DALLE BETON SOUS SOL20NON0
ISOLANT                                            NON
ISOLANT1                                           NON
ISOLANT2                                            ND
ISOLANT3                                           NON
ISOLANT4                                            ND
NUMERO_PERIODE                                      P2
PERMEABILITE                                         8
PLANCHER                    DALLE BETON SOUS SOL20NON0
PLANCHER_INTERMEDIAIRE                             NON
PLANCHER_RDC                      DALLE BETON SOUS SOL
PORTEUR                                  BRIQUE CREUSE
PORTEUR1                                      PARPAING
PORTEUR2                                            ND
PORTEUR3                                STRUCTURE BOIS
PORTEUR4                                            ND
POURCENTAGE_VITRAGE                                 25
PROTECTIONS_SOLAIRES             STORE INTERIEUR_VOLET
REVETEMENT_EXT                                  ENDUIT
REVETEMENT_EXT1                                 ENDUIT
REVETEMENT_EXT2                                     ND
REVETEMENT_EXT3                            TUILE CANAL
REVETEMENT_EXT4                                     ND
REVETEMENT_INT                                  ENDUIT
REVETEMENT_INT1                       PLAQUE DE PLATRE
REVETEMENT_INT2                                     ND
REVETEMENT_INT3                                    NON
REVETEMENT_INT4                                     ND
TERRITOIRE1                                     FRANCE
TERRITOIRE_DESC                      Territoire France
TERRITOIRE_SHORT_ID                                 TF
TYPE_VITRAGE                           SIMPLE VITRAGE
VENTILATION                                        NON
arch                               P2-P-HABITAT-FRANCE
Name: HAB_P_P2_TF, dtype: object

In [81]:
df.loc["HAB_P_P1_TVOL_ARD"].EP_ISOLANT3

12

In [81]:
df.loc["HAB_P_P1_TVOL_ARD"].EP_ISOLANT3

12

In [20]:
for ele in df["DISPOSTIIF_TOIT_ OPTION1"].unique():

HAB_T_P1_TBR_TU
HAB_T_P1_TPI_AR
HAB_T_P1_TBR_TM
HAB_T_P1_TBR_TP
HAB_T_P1_TBR_TC
SER_T_P1_TN
CHA_T_P1_TZINC
HAB_T_P1_TBR_TR
HAB_T_P4_TPI_AR
TER_T_P2_TN_BAC
SER_T_P2_TN
HAB_T_P2_TBR_TC
HAB_T_P2_TPI_AR
HAB_T_P2_TN_GR
TER_T_P3_TN_BAC
SER_T_P3_TN
HAB_T_P3_TN_TU
HAB_T_P3_TPI_AR
HAB_T_P3_TN_GR
TER_T_P4_TN_BAC
SER_T_P4_TN
HAB_T_P4_TN_TU
HAB_T_P4_TN_GR
TER_T_P5_TN_BAC
SER_T_P5_TN
HAB_T_P5_TN_TU
HAB_T_P5_TPI_AR
HAB_T_P5_TN_GR
TER_T_P6_TN_BAC
SER_T_P6_TN
HAB_T_P6_TN_TU
HAB_T_P6_TPI_AR
HAB_T_P6_TN_GR
TER_T_P7_TN_BAC
SER_T_P7_TN
HAB_T_P7_TBR_TC
HAB_T_P7_TPI_AR
HAB_T_P7_TN

In [ ]:
for df["DISPOSTIIF_TOIT_ OPTION1"].unique():
    df_1d = df[df]

In [72]:
disp_roofs = []
for disp_t in df["DISPOSTIIF_TOIT_ OPTION1"].unique():
    df_1disp = df[df["DISPOSTIIF_TOIT_ OPTION1"]==disp_t][["DISPOSITIF3",
                                                        "PORTEUR3",
                                                        "EP_PORTEUR3",
                                                        "ISOLANT3",
                                                        "EP_ISOLANT3",
                                                        "REVETEMENT_EXT3",
                                                        "EP_RE3",
                                                        "REVETEMENT_INT3",
                                                        "EP_RI3",
                                                        ]].iloc[:1]
    disp_roofs.append(df_1disp)
disp_roof = pd.concat(disp_roofs)

In [74]:
disp_roof = disp_roof.sort_values(["DISPOSITIF3"]).reset_index(drop=True)
disp_roof.to_excel("roof_disp.xlsx")

### Analyse des combinaisons possibles

#### By layer and thickness

In [51]:
disp_roof.groupby(["PORTEUR3",
                "EP_PORTEUR3",
                ]
                 ).size().reset_index().rename(columns={0:'count'})

          PORTEUR3  EP_PORTEUR3  count
0      DALLE BETON           20      6
1   STRUCTURE BOIS            0     19
2  STRUCTURE METAL            0     13

- tous les porteurs d'un même type ont la même épaisseur

In [52]:
disp_roof.groupby(["ISOLANT3",
                "EP_ISOLANT3",
                ]
                 ).size().reset_index().rename(columns={0:'count'})

  ISOLANT3  EP_ISOLANT3  count
0  ITE_POL           30      1
1   ITI_LM            5      1
2   ITI_LM            9      1
3   ITI_LM           11      1
4   ITI_LM           12      3
5   ITI_LM           14      1
6   ITI_LM           15      3
7   ITI_LM           20      3
8   ITI_LM           30      2
9      NON            0     22

- Le principal isolant est la laine minérale, que s'applique à tous les cas isolés à part un avec du polystyrène

In [53]:
disp_roof.groupby(["REVETEMENT_EXT3",
                "EP_RE3",
                ]
                 ).size().reset_index().rename(columns={0:'count'})

    REVETEMENT_EXT3  EP_RE3  count
0           ARDOISE   $2.00      7
1   COUVERTURE ZINC   $1.00      1
2    DOUBLE VITRAGE   $3.00      3
3           GRAVIER   $5.00      5
4           GRAVIER  $10.00      1
5    SIMPLE VITRAGE   $2.00      4
6              TOLE   $0.80      6
7             TUILE   $2.00      5
8            TUILE    $2.00      1
9       TUILE CANAL   $2.00      2
10  TUILE MECANIQUE   $2.00      1
11      TUILE PLATE   $2.00      1
12    TUILE ROMAINE   $2.00      1

- Les revêtements  extérieurs ont en majorité une épaisseur par type, à part le gravier.
- Il y a un espace de plus en pour le revêtement TUILE: 'TUILE', 'TUILE '.

In [55]:
disp_roof.groupby(["REVETEMENT_INT3",
                "EP_RI3",
                ]
                 ).size().reset_index().rename(columns={0:'count'})

    REVETEMENT_INT3  EP_RI3  count
0               NON   $0.00     27
1  PLAQUE DE PLATRE   $1.30     11

- Un unique type de revêtement intérieur existe, si présent : plaque de plâtre de 1,3 cm

#### By structure and covering

In [90]:
port_revext = disp_roof.groupby(["PORTEUR3",
                "REVETEMENT_EXT3",
                ]
                 ).size().reset_index().rename(columns={0:'count'})
port_revext.to_excel("Porteur_RevExt.xlsx")
port_revext

           PORTEUR3  REVETEMENT_EXT3  count
0       DALLE BETON          GRAVIER      6
1    STRUCTURE BOIS          ARDOISE      7
2    STRUCTURE BOIS  COUVERTURE ZINC      1
3    STRUCTURE BOIS            TUILE      5
4    STRUCTURE BOIS           TUILE       1
5    STRUCTURE BOIS      TUILE CANAL      2
6    STRUCTURE BOIS  TUILE MECANIQUE      1
7    STRUCTURE BOIS      TUILE PLATE      1
8    STRUCTURE BOIS    TUILE ROMAINE      1
9   STRUCTURE METAL   DOUBLE VITRAGE      3
10  STRUCTURE METAL   SIMPLE VITRAGE      4
11  STRUCTURE METAL             TOLE      6

#### By global composition

In [62]:
all_comb = disp_roof.groupby(["PORTEUR3",
                "EP_PORTEUR3",
                "ISOLANT3",
                "EP_ISOLANT3",
                "REVETEMENT_EXT3",
                "EP_RE3",
                "REVETEMENT_INT3",
                "EP_RI3"]
                 ).size().reset_index().rename(columns={0:'count'})

print("len(all_comb):", len(all_comb))
all_comb[all_comb['count'] > 1]

len(all_comb): 28

,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3,count
4,DALLE BETON,20,NON,0,GRAVIER,$5.00,NON,$0.00,2
13,STRUCTURE BOIS,0,NON,0,ARDOISE,$2.00,NON,$0.00,3
17,STRUCTURE BOIS,0,NON,0,TUILE CANAL,$2.00,NON,$0.00,2
25,STRUCTURE METAL,0,NON,0,DOUBLE VITRAGE,$3.00,NON,$0.00,3
26,STRUCTURE METAL,0,NON,0,SIMPLE VITRAGE,$2.00,NON,$0.00,4
27,STRUCTURE METAL,0,NON,0,TOLE,$0.80,NON,$0.00,2

- Au total il y a 28 combinaisons des caractheristiques de toit, comme il y a 38 dispositifs toit, certaines entre elles sont redundantes.  
- Les combinaisons ci-dessus sont répétées dans de différents dispositifs de toit

In [60]:
# combinations without insulation
disp_roof.groupby(["PORTEUR3",
                "EP_PORTEUR3",
#                 "ISOLANT3",
#                 "EP_ISOLANT3",
                "REVETEMENT_EXT3",
                "EP_RE3",
                "REVETEMENT_INT3",
                "EP_RI3"]
                 ).size().reset_index().rename(columns={0:'count'})

,PORTEUR3,EP_PORTEUR3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3,count
0,DALLE BETON,20,GRAVIER,$5.00,NON,$0.00,2
1,DALLE BETON,20,GRAVIER,$5.00,PLAQUE DE PLATRE,$1.30,3
2,DALLE BETON,20,GRAVIER,$10.00,NON,$0.00,1
3,STRUCTURE BOIS,0,ARDOISE,$2.00,NON,$0.00,3
4,STRUCTURE BOIS,0,ARDOISE,$2.00,PLAQUE DE PLATRE,$1.30,4
5,STRUCTURE BOIS,0,COUVERTURE ZINC,$1.00,NON,$0.00,1
6,STRUCTURE BOIS,0,TUILE,$2.00,NON,$0.00,1
7,STRUCTURE BOIS,0,TUILE,$2.00,PLAQUE DE PLATRE,$1.30,4
8,STRUCTURE BOIS,0,TUILE,$2.00,NON,$0.00,1
9,STRUCTURE BOIS,0,TUILE CANAL,$2.00,NON,$0.00,2
10,STRUCTURE BOIS,0,TUILE MECANIQUE,$2.00,NON,$0.00,1
11,STRUCTURE BOIS,0,TUILE PLATE,$2.00,NON,$0.00,1
12,STRUCTURE BOIS,0,TUILE ROMAINE,$2.00,NON,$0.00,1
13,STRUCTURE METAL,0,DOUBLE VITRAGE,$3.00,NON,$0.00,3
14,STRUCTURE METAL,0,SIMPLE VITRAGE,$2.00,NON,$0.00,4
15,STRUCTURE METAL,0,TOLE,$0.80,NON,$0.00,6

- Dalle béton toujours avec gravier

- A part l'epaisseur de l'isolant, il y a 17 combinaisons differentes pour le toit

 https://bricolage.linternaute.com/forum/affich-46685-comment-choisir-entre-tuile-ou-tole-pour-renovation
 La tuile a un certain rôle d'isolation et tient à peu près 80 ans. La tôle n'isole rien du tout et tient au max 30 ans

In [63]:
disp_roof[disp_roof["REVETEMENT_EXT3"]=="TOLE"]

,DISPOSITIF3,PORTEUR3,EP_PORTEUR3,ISOLANT3,EP_ISOLANT3,REVETEMENT_EXT3,EP_RE3,REVETEMENT_INT3,EP_RI3
9,TER_T_P2_TN_BAC,STRUCTURE METAL,0,NON,0,TOLE,$0.80,NON,$0.00
14,TER_T_P3_TN_BAC,STRUCTURE METAL,0,NON,0,TOLE,$0.80,NON,$0.00
19,TER_T_P4_TN_BAC,STRUCTURE METAL,0,ITI_LM,5,TOLE,$0.80,NON,$0.00
23,TER_T_P5_TN_BAC,STRUCTURE METAL,0,ITI_LM,9,TOLE,$0.80,NON,$0.00
28,TER_T_P6_TN_BAC,STRUCTURE METAL,0,ITI_LM,11,TOLE,$0.80,NON,$0.00
33,TER_T_P7_TN_BAC,STRUCTURE METAL,0,ITI_LM,14,TOLE,$0.80,NON,$0.00